3.Use numpy to do the following tasks

In [ ]:
 Task B1
# Create a 5×5 matrix where:
#   - The border (edges) cells = 1
#   - The interior cells      = 0
# Expected:
# [[1 1 1 1 1]
#  [1 0 0 0 1]
#  [1 0 0 0 1]
#  [1 0 0 0 1]
#  [1 1 1 1 1]]

B1 = None   # YOUR CODE HERE

print("B1 — Border matrix:\n", B1)


# Task B2
# Given the array below, normalise it so every value falls
# between 0 and 1 using min-max normalisation:
#   normalised = (x - min) / (max - min)

raw = np.array([10, 25, 4, 87, 56, 33, 72, 19])
B2  = None   # YOUR CODE HERE — normalise `raw`

print("B2 — Normalised array:", B2)

In [53]:
import numpy as np

# Create a 5x5 matrix of zeros
B1 = np.zeros((5,5), dtype=int)

# Set borders to 1
B1[0, :] = 1 
B1[-1, :] = 1
B1[:, 0] = 1
B1[:, -1] = 1

print("B1 - Border matrix:\n", B1)

B1 - Border matrix:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
# Using the formula given

raw = np.array([10, 25, 4, 87, 56, 33, 72, 19])

# Apply normalization
B2 = (raw - raw.min()) / (raw.max() - raw.min())
print ("B2 - Normalised array:",  

4. Use pandas to do the following

In [ ]:
data = {
    "employee_id":  [101, 102, 103, 104, 105, 106, 107, 108],
    "department":   ["Engineering", "Marketing", "Engineering",
                     "HR", "Marketing", "Engineering", "HR", "Marketing"],
    "salary":       [85000, 52000, 91000, 47000, 61000, np.nan, 43000, 58000],
    "years_exp":    [5, 3, 8, 2, 4, 6, 1, 3],
    "performance":  ["High", "Medium", "High", "Low",
                     "Medium", "High", "Low", "Medium"]}
df = pd.DataFrame(data)

# Task C1
# Fill the missing salary with the mean salary of the
# Engineering department (not the whole dataset).
# Store the cleaned DataFrame in C1_df.

C1_df = None   # YOUR CODE HERE

print("C1 — Missing salary filled:\n", C1_df[["employee_id", "department", "salary"]])

# Task C2
# Create a new column "salary_band" using these rules:
#   "Junior"  → salary < 50,000
#   "Mid"     → 50,000 ≤ salary < 80,000
#   "Senior"  → salary ≥ 80,000
# Work on C1_df (with no missing values).

C2_df = None   # YOUR CODE HERE (add column to a copy of C1_df)

print("\nC2 — With salary band:\n",
      C2_df[["employee_id", "salary", "salary_band"]] if C2_df is not None else "Not answered")


In [41]:
import pandas as pd
import numpy as np
data = {
    "employee_id":  [101, 102, 103, 104, 105, 106, 107, 108],
    "department":   ["Engineering", "Marketing", "Engineering",
                     "HR", "Marketing", "Engineering", "HR", "Marketing"],
    "salary":       [85000, 52000, 91000, 47000, 61000, np.nan, 43000, 58000],
    "years_exp":    [5, 3, 8, 2, 4, 6, 1, 3],
    "performance":  ["High", "Medium", "High", "Low",
                     "Medium", "High", "Low", "Medium"]}
df = pd.DataFrame(data)

eng_mean = df[df["department"] == "Engineering"]["salary"].mean()

df.loc[(df["department"] == "Engineering") & (df["salary"].isna()),"salary"] = eng_mean
print(df)

   employee_id   department   salary  years_exp performance
0          101  Engineering  85000.0          5        High
1          102    Marketing  52000.0          3      Medium
2          103  Engineering  91000.0          8        High
3          104           HR  47000.0          2         Low
4          105    Marketing  61000.0          4      Medium
5          106  Engineering  88000.0          6        High
6          107           HR  43000.0          1         Low
7          108    Marketing  58000.0          3      Medium


In [40]:
 # Storing the cleaned dataframe
C1_df = df.copy()
print(C1_df)

   employee_id   department   salary  years_exp performance
0          101  Engineering  85000.0          5        High
1          102    Marketing  52000.0          3      Medium
2          103  Engineering  91000.0          8        High
3          104           HR  47000.0          2         Low
4          105    Marketing  61000.0          4      Medium
5          106  Engineering  88000.0          6        High
6          107           HR  43000.0          1         Low
7          108    Marketing  58000.0          3      Medium


In [46]:
def sort_salary(salary):
    if salary < 50000:
        return "Junior"
    if 50000 <= salary < 80000:
        return "Mid"
    else:
        return "Senior"
df["salary_band"] = df["salary"].apply(sort_salary)  
print(df)

   employee_id   department   salary  years_exp performance salary_band
0          101  Engineering  85000.0          5        High      Senior
1          102    Marketing  52000.0          3      Medium         Mid
2          103  Engineering  91000.0          8        High      Senior
3          104           HR  47000.0          2         Low      Junior
4          105    Marketing  61000.0          4      Medium         Mid
5          106  Engineering  88000.0          6        High      Senior
6          107           HR  43000.0          1         Low      Junior
7          108    Marketing  58000.0          3      Medium         Mid


In [48]:
C1_df = C1_df.dropna()
print(C1_df)

   employee_id   department   salary  years_exp performance
0          101  Engineering  85000.0          5        High
1          102    Marketing  52000.0          3      Medium
2          103  Engineering  91000.0          8        High
3          104           HR  47000.0          2         Low
4          105    Marketing  61000.0          4      Medium
5          106  Engineering  88000.0          6        High
6          107           HR  43000.0          1         Low
7          108    Marketing  58000.0          3      Medium


In [49]:
C2_df = None   # YOUR CODE HERE (add column to a copy of C1_df)

print("\nC2 — With salary band:\n",
      C2_df[["employee_id", "salary", "salary_band"]] if C2_df is not None else "Not answered")



C2 — With salary band:
 Not answered
